# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2
      # Install Heroku CLI.
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # Add explicit login to Heroku Container Registry
      - name: Login to Heroku Container Registry
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=${{ secrets.HEROKU_EMAIL }} --password-stdin registry.heroku.com
      
      # Verify Heroku app exists
      - name: Verify Heroku app
        run: |
          heroku apps:info ${{ secrets.HEROKU_APP_NAME }} --json || heroku apps:create ${{ secrets.HEROKU_APP_NAME }}
        env:

      - name: Deploy directly with Heroku CLI
        run: 
        # Log in to Heroku
         echo "${{ secrets.HEROKU_API_KEY }}" | heroku container:login 
        # Build and push the Docker image  
         docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
         docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
         # Release the container
         heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}  
    env:
    HEROKU_API_KEY  : ${{ secrets.HEROKU_API_KEY }}


